use lazy_static::lazy_static;

lazy_static! {
    pub static ref GOOD_LINKS: Vec<String> = vec![
        "minecraft.org".to_string(),
        "minecraft.net".to_string(),
        "netty.io".to_string(),
        "optifine.net".to_string(),
        "mojang.com".to_string(),
        "apache.org".to_string(),
        "logging.apache.org".to_string(),
        "www.w3.org".to_string(),
        "tools.ietf.org".to_string(),
        "eclipse.org".to_string(),
        "www.openssl.org".to_string(),
        "sessionserver.mojang.com".to_string(),
        "authserver.mojang.com".to_string(),
        "api.mojang.com".to_string(),
        "shader-tutorial.dev".to_string(),
        "s.optifine.net".to_string(),
        "snoop.minecraft.net".to_string(),
        "account.mojang.com".to_string(),
        "bugs.mojang.com".to_string(),
        "aka.ms".to_string(),
        "minotar.net".to_string(),
        "dominos.com".to_string(),
        "cabaletta/baritone".to_string(),
        "yaml.org".to_string(),
        "java.sun.org".to_string(),
        "com/viaversion/".to_string(),
        "lwjgl.org".to_string(),
        "dump.viaversion.com".to_string(),
        "docs.advntr.dev".to_string(),
        "jo0001.github.io".to_string(),
        "viaversion.com".to_string(),
        "ci.viaversion.com".to_string(),
        "paulscode/sound/".to_string(),
        "api.spiget.org".to_string(),
        "login.live.com".to_string(),
        "www.slf4j.org".to_string(),
        "www.rfc-editor.org".to_string()
    ];
}
