name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-overlay:
    name: collapsescanner
    runs-on: windows-latest

    steps:
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Build
        run: |
          cargo build --verbose --release
          $ARTIFACT_HASH=git rev-parse --short HEAD
          echo "ARTIFACT_HASH=$ARTIFACT_HASH" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

      - name: Rename Executable
        id: rename
        run: copy target/release/collapsescanner.exe ./collapsescanner-${{ env.ARTIFACT_HASH }}.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build_${{ env.ARTIFACT_HASH }}
          path: collapsescanner-${{ env.ARTIFACT_HASH }}.exe